# Generated by Django 4.2.4 on 2023-08-20 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code', models.CharField(choices=[('A', 'Acquisition Deliverables'), ('FT', 'Fast-Track PSDM'), ('FI', 'Full-Integrity PSDM'), ('N', 'No Product')], max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('stage', models.CharField(choices=[('PL', 'Planned'), ('Ongoing', 'Ongoing'), ('CP', 'Completed')], max_length=10)),
                ('products', models.ManyToManyField(related_name='projects', to='suriname.product')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DR', 'Data Review'), ('P', 'Proposal'), ('N', 'No Contact'), ('C', 'Contacted'), ('L', 'Licensed')], max_length=2)),
                ('date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='suriname.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suriname.project')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suriname.manager'),
        ),
    ]
