# Generated by Django 4.2.4 on 2023-08-20 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suriname', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('CP', 'Completed'), ('PL', 'Planned')], max_length=10),
        ),
        migrations.AlterField(
            model_name='status',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suriname.company'),
        ),
    ]
