# Generated by Django 4.2.4 on 2023-08-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suriname', '0002_alter_project_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Planned', 'Planned'), ('Ongoing', 'Ongoing')], max_length=20),
        ),
    ]
